// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprgXZzpvKzWdKBhbYFKHawMH9HUID06Y',
    appId: '1:211163370475:web:326defe50791e93f697fae',
    messagingSenderId: '211163370475',
    projectId: 'fintech-bridge',
    authDomain: 'fintech-bridge.firebaseapp.com',
    storageBucket: 'fintech-bridge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_3UelUs_dHI6gpWOV6nrvFXwT7XUA3g',
    appId: '1:211163370475:android:622645d09c88ec50697fae',
    messagingSenderId: '211163370475',
    projectId: 'fintech-bridge',
    storageBucket: 'fintech-bridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdXwuo1GoecD8ukDmBJoEe9n8a_mlo3Ag',
    appId: '1:211163370475:ios:c2aaf4eded4b497c697fae',
    messagingSenderId: '211163370475',
    projectId: 'fintech-bridge',
    storageBucket: 'fintech-bridge.firebasestorage.app',
    iosClientId: '211163370475-k5p6ptsknhd1vdkf35bmt4j90u19vf46.apps.googleusercontent.com',
    iosBundleId: 'com.debra.fintechBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdXwuo1GoecD8ukDmBJoEe9n8a_mlo3Ag',
    appId: '1:211163370475:ios:c2aaf4eded4b497c697fae',
    messagingSenderId: '211163370475',
    projectId: 'fintech-bridge',
    storageBucket: 'fintech-bridge.firebasestorage.app',
    iosClientId: '211163370475-k5p6ptsknhd1vdkf35bmt4j90u19vf46.apps.googleusercontent.com',
    iosBundleId: 'com.debra.fintechBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDprgXZzpvKzWdKBhbYFKHawMH9HUID06Y',
    appId: '1:211163370475:web:66684c9df7a37a8f697fae',
    messagingSenderId: '211163370475',
    projectId: 'fintech-bridge',
    authDomain: 'fintech-bridge.firebaseapp.com',
    storageBucket: 'fintech-bridge.firebasestorage.app',
  );
}
